language: node_js
node_js:
  - "8.9.1"
cache:
  directories:
    - "node_modules"
script: 
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org
  target-branch: master
  local-dir: dist
  on:
    branch: dev