language: node_js
node_js:
  - "lts/8.9.1"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
script: 
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  target-branch: master
  local-dir: dist
  on:
    branch: dev